name: Tag

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Tag
        run: |
          ./gradlew getVersionNumber
          git config --global user.email "massi@massi.dev"
          git config --global user.name "Massimiliano Cannarozzo"
          git tag -a $(cat MuzeiWebcam/versionNumber) -m "$(cat MuzeiWebcam/versionNumber)"
          git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --tags
